name: Integrate

on:
  push: {}

permissions: {}

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 7.19.0
          - 7.20.0
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Fetch dependencies
        env:
          PNPM_VERSION: ${{ matrix.version }}
        run: |
          docker build \
            --build-arg PNPM_VERSION \
            --tag "ci:${PNPM_VERSION}" \
            .

      - name: Install dependencies
        env:
          PNPM_VERSION: ${{ matrix.version }}
        run: |
          docker run \
            --volume "${PWD}/:/workdir" \
            --volume /workdir/.pnpm-store \
            "ci:${PNPM_VERSION}" \
            sh \
            -c \
            'pnpm install --offline --recursive'
