name: Integrate

on:
  push: {}

permissions: {}

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 7.19.0
          - 7.20.0
          - 7.21.0
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        env:
          PNPM_VERSION: ${{ matrix.version }}
        run: ./install.sh
